### ISSUE TITLE
plugin vagrant-disksize can't be used on Apple Silicon

### ISSUE THREAD

**Issue by xuerbujia** [oferchen/killer-sh-vagrant#1]
hello,I specified provider as vmware_fusion: vagrant up --provider=vmware_fusion, but it still reports an error Vagrant could not detect VirtualBox Because [sprotheroe/vagrant-disksize#45](https://github.com/sprotheroe/vagrant-disksize/issues/45). Are there other method don't need plugin vagrant-disksize?

**Comment by oferchen** [comment]
I removed the requirement for arm64 architecture until issue will be fixed upstream, if I remember correctly this is not required for fusion.

**Comment by oferchen** [comment]
unfortunately this issue was not resolved completely yet.

**Comment by oferchen** [comment]
situation is now resolved, please submit a new issue if you are still experiencing issues.

**Comment by xuerbujia** [comment]
Thank you. It was successfully ran

**Comment by oferchen** [comment]
excellent.
